// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/eitan/.local/share/flatpak/exports/share/gir-1.0
// from /home/eitan/Projects/spiel/libspeechprovider/build/libspeechprovider
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from /var/lib/flatpak/exports/share/gir-1.0
// DO NOT EDIT

mod stream_writer;
pub use self::stream_writer::StreamWriter;

mod enums;
pub use self::enums::EventType;

mod flags;
pub use self::flags::VoiceFeature;

