// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/eitan/.local/share/flatpak/exports/share/gir-1.0
// from /home/eitan/Projects/spiel/libspeechprovider/build/libspeechprovider
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from /var/lib/flatpak/exports/share/gir-1.0
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "SpeechProviderChunkType", sizeof(SpeechProviderChunkType), alignof(SpeechProviderChunkType));
    printf("%s;%zu;%zu\n", "SpeechProviderEventData", sizeof(SpeechProviderEventData), alignof(SpeechProviderEventData));
    printf("%s;%zu;%zu\n", "SpeechProviderEventType", sizeof(SpeechProviderEventType), alignof(SpeechProviderEventType));
    printf("%s;%zu;%zu\n", "SpeechProviderStreamHeader", sizeof(SpeechProviderStreamHeader), alignof(SpeechProviderStreamHeader));
    printf("%s;%zu;%zu\n", "SpeechProviderStreamReaderClass", sizeof(SpeechProviderStreamReaderClass), alignof(SpeechProviderStreamReaderClass));
    printf("%s;%zu;%zu\n", "SpeechProviderStreamWriterClass", sizeof(SpeechProviderStreamWriterClass), alignof(SpeechProviderStreamWriterClass));
    printf("%s;%zu;%zu\n", "SpeechProviderVoiceFeature", sizeof(SpeechProviderVoiceFeature), alignof(SpeechProviderVoiceFeature));
    return 0;
}
